name: Publish to GitHub Pages

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  pages:    write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish:
    name: Generate & Publish PHPDoc
    environment:
      name: github-pages
      url: ${{ steps.publish-phpdoc.outputs.page-url }}
    runs-on: ubuntu-latest
    steps:
      - name: Publish PHPDoc
        id:   publish-phpdoc
        uses: empaphy/dev/actions/publish-phpdoc@v1
